// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class Column_Menu_Ruta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Column_Menu_Ruta));
        
        string IMigrationMetadata.Id
        {
            get { return "202003162238365_Column_Menu_Ruta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
