CREATE TABLE [dbo].[tblTransactionDocumentDets]
(
	[IdTransactionDocumentDets] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [IdTransactionDocument] UNIQUEIDENTIFIER NOT NULL, 
    [DocumentCode] VARCHAR(50) NOT NULL, 
    [SerieCode] VARCHAR(50) NOT NULL, 
    [NumDocument] VARCHAR(50) NOT NULL, 
    [Item] BIGINT NOT NULL, 
    [WareHouseCode] VARCHAR(50) NOT NULL, 
    [ProductCode] VARCHAR(50) NOT NULL, 
    [Description] VARCHAR(500) NOT NULL, 
    [BranchCode] VARCHAR(50) NOT NULL, 
    [PriceListCod] VARCHAR(50) NOT NULL, 
    [MovementDate] DATETIME NOT NULL, 
    [Details] VARCHAR(MAX) NOT NULL, 
    [OriginDocumentCode] VARCHAR(50) NOT NULL, 
    [OriginSerieCode] VARCHAR(50) NOT NULL, 
    [NumDocumentOrigin] BIGINT NULL, 
    [ItemOrigin] BIGINT NULL, 
    [VendorCode] VARCHAR(50) NOT NULL, 
    [UnitMeasureCode] VARCHAR(50) NULL, 
    [ValueUnitary] FLOAT NOT NULL, 
    [QuantityOpen] FLOAT NOT NULL, 
    [Quantity] FLOAT NOT NULL, 
    [ValueGross] FLOAT NOT NULL, 
    [Discount] FLOAT NULL, 
    [DiscountPromotional] FLOAT NULL, 
    [DiscountAdditional] FLOAT NULL, 
    [DiscountFinal] FLOAT NULL, 
    [ValueDiscount] FLOAT NOT NULL, 
    [ValueTrasDiscount] FLOAT NOT NULL, 
    [ValueNetUnitary] FLOAT NOT NULL, 
    [DutyCode] FLOAT NOT NULL, 
    [TariffDuty] FLOAT NOT NULL, 
    [ValueDutty] FLOAT NOT NULL, 
    [ValueRetention] FLOAT NOT NULL, 
    [ValueTotal] FLOAT NOT NULL, 
    [CostAverangeCurrent] FLOAT NOT NULL, 
    [CostAverange] FLOAT NOT NULL, 
    [ItemInventary] BIT NOT NULL, 
    [StateLine] VARCHAR(50) NULL, 
    [DistributionCode] VARCHAR(50) NULL, 
    [ApplyAloneDutty] BIT NOT NULL, 
    [Sync] BIT NOT NULL, 
    [SyncDate] DATETIME NULL, 
    [UserCode] VARCHAR(50) NULL, 
    [AdrressIp] VARCHAR(500) NULL, 
    CONSTRAINT [FK_tblTransactionDocumentDets_tblTransactionDocument] FOREIGN KEY ([IdTransactionDocument]) REFERENCES [tblTransactionDocument]([IdTransactionDocument])
)
