CREATE TABLE [dbo].[tblTransactionDocument]
(
	[TransactionDocumentId] INT NOT NULL PRIMARY KEY IDENTITY,
    [DocumentCode] VARCHAR(10) NOT NULL, 
    [SerieCode] VARCHAR(10) NOT NULL, 
    [NumDocument] BIGINT NOT NULL, 
    [DocumentDate] DATETIME NOT NULL, 
    [AccountingDate] DATETIME NOT NULL, 
    [ExpirationDate] DATETIME NOT NULL, 
    [CreationDate] DATETIME NOT NULL, 
    [ProviderCode] VARCHAR(50) NULL, 
    [IdentificationNumber] VARCHAR(50) NOT NULL, 
    [ThirdName] VARCHAR(500) NULL, 
    [TradeName] VARCHAR(500) NULL, 
    [PriceListCode] VARCHAR(10) NOT NULL, 
    [PopulationCode] VARCHAR(50) NULL, 
    [Address] VARCHAR(250) NULL, 
    [Telephone] VARCHAR(50) NULL, 
    [PaymentConditionCode] VARCHAR(50) NULL, 
    [Period] INT NULL, 
    [CurrencyCode] VARCHAR(50) NULL, 
    [Draft] BIT NOT NULL, 
    [Comments] VARCHAR(MAX) NULL, 
    [CommentsAccounting] VARCHAR(MAX) NULL, 
    [AssociatedAccount] VARCHAR(50) NULL, 
    [TotalGross] FLOAT NOT NULL, 
    [TotalDiscount] FLOAT NOT NULL, 
    [TotalTrasDiscount] FLOAT NOT NULL, 
    [TotalDuty] FLOAT NOT NULL, 
    [TotalRetention] FLOAT NOT NULL, 
    [TotalRound] FLOAT NOT NULL, 
    [TotalDocument] FLOAT NOT NULL, 
    [TotalCost] FLOAT NOT NULL, 
    [ValueTrmNegotiation] FLOAT NULL, 
    [StateDocument] VARCHAR(50) NOT NULL, 
    [DocRef] VARCHAR(50) NULL, 
    [NumberPrinting] INT NULL, 
    [Prefix] VARCHAR(50) NULL, 
    [Suffix] VARCHAR(50) NULL, 
    [FinancialDiscount] FLOAT NULL, 
    [FinancialDiscountDate] DATETIME NULL, 
    [AffectCost] BIT NOT NULL, 
    [RetentionNA] BIT NOT NULL, 
    [Title] VARCHAR(500) NULL, 
    [SubTitle] VARCHAR(500) NULL, 
    [Legend1] VARCHAR(500) NULL, 
    [Legend2] VARCHAR(500) NULL, 
    [Legend3] VARCHAR(500) NULL, 
    [Legend4] VARCHAR(500) NULL, 
    [Legend5] VARCHAR(500) NULL, 
    [Legend6] VARCHAR(500) NULL, 
    [Legend7] VARCHAR(500) NULL, 
    [Legend8] VARCHAR(500) NULL, 
    [Legend9] VARCHAR(500) NULL, 
    [Legend10] VARCHAR(500) NULL, 
    [OperationType] VARCHAR(2) NULL, 
    [UserCode] VARCHAR(50) NULL, 
    [IPAdrress] VARCHAR(50) NULL, 
    [Sync] BIT NOT NULL DEFAULT 0, 
    [SyncDate] DATETIME NULL, 
    CONSTRAINT [FK_tblTransactionDocument_TblDocuments] FOREIGN KEY (DocumentCode) REFERENCES [dbo].[TblDocuments](DocumentCode), 
    CONSTRAINT [FK_tblTransactionDocument_TblSeries] FOREIGN KEY (SerieCode) REFERENCES [dbo].[TblSeries](SerieCode), 
    CONSTRAINT [FK_tblTransactionDocument_TblPriceList] FOREIGN KEY (PriceListCode) REFERENCES [dbo].[tblPriceList](PriceListCode)

)
