CREATE TABLE [dbo].[tblTransactionDocumentDets]
(
	[IdTransactionDocumentDets] INT NOT NULL PRIMARY KEY IDENTITY, 
    [IdTransactionDocument] INT NOT NULL, 
    [DocumentCode] VARCHAR(10) NOT NULL, 
    [SerieCode] VARCHAR(10) NOT NULL, 
    [NumDocument] VARCHAR(50) NOT NULL, 
    [Item] BIGINT NOT NULL, 
    [WareHouseCode] VARCHAR(10) NOT NULL, 
    [ProductCode] VARCHAR(50) NOT NULL, 
    [Description] VARCHAR(500) NOT NULL, 
    [PriceListCode] VARCHAR(10) NOT NULL, 
    [MovementDate] DATETIME NOT NULL, 
    [Details] VARCHAR(MAX) NOT NULL, 
    [OriginDocumentCode] VARCHAR(50) NULL, 
    [OriginSerieCode] VARCHAR(50) NULL, 
    [NumDocumentOrigin] BIGINT NULL, 
    [ItemOrigin] BIGINT NULL, 
    [VendorCode] VARCHAR(50) NOT NULL, 
    [UnitMeasureCode] VARCHAR(20) NULL, 
    [ValueUnitary] FLOAT NOT NULL, 
    [QuantityOpen] FLOAT NOT NULL, 
    [Quantity] FLOAT NOT NULL, 
    [ValueGross] FLOAT NOT NULL, 
    [Discount] FLOAT NULL, 
    [DiscountPromotional] FLOAT NULL, 
    [DiscountAdditional] FLOAT NULL, 
    [DiscountFinal] FLOAT NULL, 
    [ValueDiscount] FLOAT NOT NULL, 
    [ValueTrasDiscount] FLOAT NOT NULL, 
    [ValueNetUnitary] FLOAT NOT NULL, 
    [DutyCode] VARCHAR(10) NOT NULL, 
    [TariffDuty] FLOAT NOT NULL, 
    [ValueDutty] FLOAT NOT NULL, 
    [ValueRetention] FLOAT NOT NULL, 
    [ValueTotal] FLOAT NOT NULL, 
    [CostAverangeCurrent] FLOAT NOT NULL, 
    [CostAverange] FLOAT NOT NULL, 
    [ItemInventary] BIT NOT NULL, 
    [StateLine] VARCHAR(50) NULL, 
    [ApplyAloneDutty] BIT NOT NULL, 
    [Sync] BIT NOT NULL, 
    [SyncDate] DATETIME NULL, 
    [UserCode] VARCHAR(50) NULL, 
    [AdrressIp] VARCHAR(500) NULL, 
    CONSTRAINT [FK_tblTransactionDocumentDets_tblTransactionDocument] FOREIGN KEY ([IdTransactionDocument]) REFERENCES [tblTransactionDocument]([TransactionDocumentId]), 
    CONSTRAINT [FK_tblTransactionDocumentDets_TblDocuments] FOREIGN KEY (DocumentCode) REFERENCES [TblDocuments](DocumentCode),
    CONSTRAINT [FK_tblTransactionDocumentDets_TblSeries] FOREIGN KEY (SerieCode) REFERENCES [TblSeries](SerieCode),
    CONSTRAINT [FK_tblTransactionDocumentDets_TblProduct] FOREIGN KEY (ProductCode) REFERENCES [TblProduct](ProductCode),
    CONSTRAINT [FK_tblTransactionDocumentDets_TblWarehouse] FOREIGN KEY (WarehouseCode) REFERENCES [TblWarehouse](WarehouseCode),
    CONSTRAINT [FK_tblTransactionDocumentDets_TblPriceList] FOREIGN KEY (PriceListCode) REFERENCES [dbo].[tblPriceList](PriceListCode),
    CONSTRAINT [FK_tblTransactionDocumentDets_TblDuty] FOREIGN KEY ([DutyCode]) REFERENCES [dbo].[TblDuty](DutyCode), 
    CONSTRAINT [FK_tblTransactionDocumentDets_TblMeasure] FOREIGN KEY (UnitMeasureCode) REFERENCES [TblMeasure](Measurecode)
)
