CREATE TABLE [dbo].[tblTransactionDocument]
(
	[IdTransactionDocument] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [DocumentCode] VARCHAR(50) NOT NULL, 
    [SerieCode] VARCHAR(50) NOT NULL, 
    [NumDocument] BIGINT NOT NULL, 
    [DocumentDate] DATETIME NOT NULL, 
    [AccountingDate] DATETIME NOT NULL, 
    [ExpirationDate] DATETIME NOT NULL, 
    [CreationDate] DATETIME NOT NULL, 
    [PartnerCod] VARCHAR(50) NOT NULL, 
    [IdentificationNumber] VARCHAR(50) NOT NULL, 
    [ThirdName] VARCHAR(500) NOT NULL, 
    [TradeName] VARCHAR(500) NOT NULL, 
    [PriceListCod] VARCHAR(50) NOT NULL, 
    [PopulationCod] VARCHAR(50) NOT NULL, 
    [Address] VARCHAR(250) NOT NULL, 
    [Telephone] VARCHAR(50) NOT NULL, 
    [PaymentConditionCode] VARCHAR(50) NOT NULL, 
    [Period] INT NOT NULL, 
    [CurrencyCode] VARCHAR(50) NOT NULL, 
    [Draft] BIT NOT NULL, 
    [Comments] VARCHAR(MAX) NOT NULL, 
    [CommentsAccounting] VARCHAR(MAX) NOT NULL, 
    [AssociatedAccount] VARCHAR(50) NOT NULL, 
    [BranchCode] VARCHAR(50) NOT NULL, 
    [TotalGross] FLOAT NOT NULL, 
    [TotalDiscount] FLOAT NOT NULL, 
    [TotalTrasDiscount] FLOAT NOT NULL, 
    [TotalDuty] FLOAT NOT NULL, 
    [TotalRetention] FLOAT NOT NULL, 
    [TotalRound] FLOAT NOT NULL, 
    [TotalDocument] FLOAT NOT NULL, 
    [TotalCost] FLOAT NOT NULL, 
    [ValueTrmNegotiation] FLOAT NOT NULL, 
    [DistributionCode] VARCHAR(50) NULL, 
    [StateDocument] VARCHAR(50) NOT NULL, 
    [DocRef] VARCHAR(50) NULL, 
    [StateAuthorizationCode] VARCHAR(50) NULL, 
    [NumberPrinting] INT NULL, 
    [Prefix] VARCHAR(50) NULL, 
    [Suffix] VARCHAR(50) NULL, 
    [FinancialDiscount] FLOAT NULL, 
    [FinancialDiscountDate] DATETIME NULL, 
    [AffectCost] BIT NOT NULL, 
    [RetentionNA] BIT NOT NULL, 
    [Title] VARCHAR(500) NULL, 
    [SubTitle] VARCHAR(500) NULL, 
    [Legend1] VARCHAR(500) NULL, 
    [Legend2] VARCHAR(500) NULL, 
    [Legend3] VARCHAR(500) NULL, 
    [Legend4] VARCHAR(500) NULL, 
    [Legend5] VARCHAR(500) NULL, 
    [Legend6] VARCHAR(500) NULL, 
    [Legend7] VARCHAR(500) NULL, 
    [Legend8] VARCHAR(500) NULL, 
    [Legend9] VARCHAR(500) NULL, 
    [Legend10] VARCHAR(500) NULL, 
    [OperationType] VARCHAR(2) NULL, 
    [UserCode] VARCHAR(50) NULL, 
    [IPAdrress] VARCHAR(50) NULL, 
    [Sync] BIT NOT NULL DEFAULT 0, 
    [SyncDate] DATETIME NULL
)
